#!/bin/bash

STRING="$(hostname --fqdn)"

# EXAMPLE HOSTNAME
# aws = DATACENTRE
# dev = ENVIRONMENT
# server1 = HOSTNAME

#STRING="aws-dev-server1"

# BREAK DOWN HOSTNAME INTO SECTIONS

DATACENTRE=`echo $STRING | cut -d- -f1`
ENVIRONMENT=`echo $STRING | cut -d- -f2`
HOSTPART=`echo $STRING | cut -d- -f3`

# COLOURS:

RED_1="41"
RED_2="31"
YELLOW_1="43"
YELLOW_2="33"
GREEN_1="42"
GREEN_2="32"
BLUE_1="36"
BLUE_2="46"
WHITE_1="39"
WHITE_2="49"

# COLOURIZE THE ENVIRONMENT SECTION OF PROMPT

case $ENVIROMENT in
"prod")
 _ROOT_ENVIRONMENT_COLOR="$RED_2"
 _USER_ENVIRONMENT_COLOR="$RED_2"
 ;;
"qa")
  _ROOT_ENVIRONMENT_COLOR="$YELLOW_2"
  _USER_ENVIRONMENT_COLOR="$YELLOW_2"
 ;;
"dev")
 _ROOT_ENVIRONMENT_COLOR="$GREEN_2"
 _USER_ENVIRONMENT_COLOR="$GREEN_2"
 ;;
*)
  _ROOT_ENVIRONMENT_COLOR="$WHITE_2"
  _USER_ENVIRONMENT_COLOR="$WHITE_2"
esac

# COLOURIZE THE DATACENTRE SECTION OF PROMPT

case $DATACENTRE in
"msa*")
  _ROOT_DATACENTRE_COLOR="$BLUE_2"
  _USER_DATACENTRE_COLOR="$BLUE_2"
  ;;
"aws*")
  _ROOT_DATACENTRE_COLOR="$YELLOW_2"
  _USER_DATACENTRE_COLOR="$YELLOW_2"
  ;;
"gcp*")
  _ROOT_DATACENTRE_COLOR="$GREEN_2"
  _USER_DATACENTRE_COLOR="$GREEN_2"
  ;;
*)
  _ROOT_DATACENTRE_COLOR="$WHITE_1"
  _USER_DATACENTRE_COLOR="$WHITE_1"
  ;;
esac

# COLOURIZE THE HOST SECTION OF PROMPT

case $HOSTPART in
*)
    _ROOT_HOSTPART_COLOR="$RED_1"
    _USER_HOSTPART_COLOR="${_USER_ENVIRONMENT_COLOR}"
    ;;
esac

# SETUP PROMPT STYLING FOR ROOT USER

DATACENTRE_ROOT="\[\033[01;${_ROOT_DATACENTRE_COLOR}m\]$DATACENTRE\[\033[00m\]"
ENVIROMENT_ROOT="\[\033[01;${_ROOT_ENVIRONMENT_COLOR}m\]$ENVIRONMENT\[\033[00m\]"
HOSTPART_ROOT="\[\033[01;${_ROOT_HOSTPART_COLOR}m\]\u@$HOSTPART\[\033[00m\]"

# SETUP PROMPT STYLING FOR OTHER USERS

DATACENTRE_USER="\[\033[01;${_USER_DATECENTRE_COLOR}m\]$DATACENTRE\[\033[00m\]"
ENVIROMENT_USER="\[\033[01;${_USER_ENVIRONMENT_COLOR}m\]$ENVIRONMENT\[\033[00m\]"
HOSTPART_USER="\[\033[01;${_USER_HOSTPART_COLOR}m\]\u@$HOSTPART\[\033[00m\]"

# SET PROMPTS

if [ "`id -u`" -eq 0 ]; then
  # ROOT USER
  PS1="(${DATACENTRE_ROOT} ${ENVIROMENT_ROOT}) ${HOSTPART_ROOT}\[\033[01;34m\] \w #\[\033[00m\] "
else
  # OTHER USERS
  PS1="(${DATACENTRE_USER} ${ENVIROMENT_USER}) ${HOSTPART_USER}\[\033[01;34m\] \w $\[\033[00m\] "
fi
