#!/bin/bash

_HOSTNAME="$(hostname --fqdn)"

# EXAMPLE HOSTNAME
# aws = DATACENTRE e.g. aws, gcp, azure, etc..
# dev = ENVIRONMENT e.g. testing, staging production, etc..
# server1 = HOST e.g. webserver01, firewall01, etc..

#_HOSTNAME="aws-dev-server1"

# BREAK DOWN HOSTNAME INTO SECTIONS

# YOU WILL NEED TO EDIT THE BELOW IN ORDER TO
# MATCH UP YOUR HOSTNAMES CORRECTLY

s="-" # SEPERATOR

_DATACENTRE=$(echo ${_HOSTNAME} | cut -d$s -f1)
_ENVIRONMENT=$(echo ${_HOSTNAME} | cut -d$s -f2)
_HOST=$(echo ${_HOSTNAME} | cut -d$s -f3)

# COLOURS:

RED_1="41"
RED_2="31"
YELLOW_1="43"
YELLOW_2="33"
GREEN_1="42"
GREEN_2="32"
BLUE_1="36"
BLUE_2="46"
WHITE_1="39"
WHITE_2="49"

# COLOURIZE THE ENVIRONMENT SECTION OF PROMPT

case $_ENVIROMENT in
"prod")
 _ROOT_ENVIRONMENT_COLOR="$RED_2"
 _USER_ENVIRONMENT_COLOR="$RED_2"
 ;;
"qa")
  _ROOT_ENVIRONMENT_COLOR="$YELLOW_2"
  _USER_ENVIRONMENT_COLOR="$YELLOW_2"
 ;;
"dev")
 _ROOT_ENVIRONMENT_COLOR="$GREEN_2"
 _USER_ENVIRONMENT_COLOR="$GREEN_2"
 ;;
*)
  _ROOT_ENVIRONMENT_COLOR="$WHITE_2"
  _USER_ENVIRONMENT_COLOR="$WHITE_2"
esac

# COLOURIZE THE DATACENTRE SECTION OF PROMPT

case $_DATACENTRE in
"msa*")
  _ROOT_DATACENTRE_COLOR="$BLUE_2"
  _USER_DATACENTRE_COLOR="$BLUE_2"
  ;;
"aws*")
  _ROOT_DATACENTRE_COLOR="$YELLOW_2"
  _USER_DATACENTRE_COLOR="$YELLOW_2"
  ;;
"gcp*")
  _ROOT_DATACENTRE_COLOR="$GREEN_2"
  _USER_DATACENTRE_COLOR="$GREEN_2"
  ;;
*)
  _ROOT_DATACENTRE_COLOR="$WHITE_1"
  _USER_DATACENTRE_COLOR="$WHITE_1"
  ;;
esac

# COLOURIZE THE HOST SECTION OF PROMPT

case $_HOST in
*)
    _ROOT_HOST_COLOR="$RED_1"
    _USER_HOST_COLOR="${_USER_ENVIRONMENT_COLOR}"
    ;;
esac

# SETUP PROMPT STYLING FOR ROOT USER

_DATACENTRE_ROOT="\[\033[01;${_ROOT_DATACENTRE_COLOR}m\]$DATACENTRE\[\033[00m\]"
_ENVIROMENT_ROOT="\[\033[01;${_ROOT_ENVIRONMENT_COLOR}m\]$ENVIRONMENT\[\033[00m\]"
_HOST_ROOT="\[\033[01;${_ROOT_HOSTPART_COLOR}m\]\u@$HOSTPART\[\033[00m\]"

# SETUP PROMPT STYLING FOR OTHER USERS

_DATACENTRE_USER="\[\033[01;${_USER_DATECENTRE_COLOR}m\]$DATACENTRE\[\033[00m\]"
_ENVIROMENT_USER="\[\033[01;${_USER_ENVIRONMENT_COLOR}m\]$ENVIRONMENT\[\033[00m\]"
_HOSTPART_USER="\[\033[01;${_USER_HOSTPART_COLOR}m\]\u@$HOSTPART\[\033[00m\]"

# SET PROMPTS

if [ "`id -u`" -eq 0 ]; then
  # ROOT USER
  PS1="(${_DATACENTRE_ROOT} ${_ENVIROMENT_ROOT}) ${_HOST_ROOT}\[\033[01;34m\] \w #\[\033[00m\] "
else
  # OTHER USERS
  PS1="(${_DATACENTRE_USER} ${_ENVIROMENT_USER}) ${_HOST_USER}\[\033[01;34m\] \w $\[\033[00m\] "
fi
